version: '3'

services:
  postgres:
    build: ./postgres
    restart: "always"
    environment:
    - POSTGRES_DB=certificate
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgresdb:/usr/src/db
    ports:
    - 5432:5432 # host port: container port

  etl :
    build: ./etl 
    environment:
      - POSTGRES_DB=certificate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    ports:
      - 8080:8080


